title: A Data Scientist's Studies
email: 
description: > # this means to ignore newlines until "author:"
  Blog posts on data science, machine learning and related topics.
author: Bronwen C.
baseurl: "" # the subpath of your site, e.g. /blog
# header-img: img/home-bg.png
url: "https://bronwencc.github.io"

copyright_name: Bronwen Cohn-Cort

# Social Profiles
twitter_username: 
github_username: bronwencc
facebook_username: 
instagram_username: 
linkedin_username: bcohncort

# Build settings
markdown: kramdown
paginate: 5
paginate_path: "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
