# Site settings
author: Bronwen C.
title: A Data Scientist's Studies
header-img: img/home-bg.png
email: 
copyright_name: Bronwen Cohn-Cort
description: > # this means to ignore newlines until "baseurl:"
  Blog posts on data science, machine learning and related topics.
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username: bronwencc
linkedin_username: bcohncort
facebook_username: 

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
