# Site settings
author: Bronwen C.
title: A Data Scientist's Studies
header-img: img/home-bg.png
email: 42773501+bronwencc@users.noreply.github.com
copyright_name: Bronwen Cohn-Cort
description: > # this means to ignore newlines until "baseurl:"
  Blog post topics from Flatiron School's Data Science course
baseurl: "/blog" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  bronwencc
linkedin_username: bcohncort

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
